### ISSUE TITLE
You don't say which version of node to use

### ISSUE THREAD

**Issue by SgtPooki** [tahnik/react-express-webpack-babel#1]
I've run into a few different issues trying to get this running.. I think knowing the following would help a lot:

1. What version of node are you using?
2. What commands do you run to install the app?
2. What command do you run to run the app?

**Comment by tahnik** [comment]
I've added that to readme now. Sorry I should have been more clear.

1. I have tested it on node v7.2.1 and v7.0.0

2. Clone the repo and open a terminal inside the directory. Run

`npm install`

 and then

`webpack`

finally

`npm start`

3. Once you have ran npm start, go to your browser and open http://localhost:3000
